#!/bin/sh
#
# CircleMUD 3.0 autorun script
# Contributions by Fred Merkel, Stuart Lamble, and Jeremy Elson
# Copyright (c) 1996 The Trustees of The Johns Hopkins University
# All Rights Reserved
# See license.doc for more information
#
#############################################################################
#
# This script can be used to run CircleMUD over and over again (i.e., have it
# automatically reboot if it crashes).  It will run the game, and copy some
# of the more useful information from the system logs to the 'log' directory
# for safe keeping.
#
# You can control the operation of this script by creating and deleting files
# in Circle's root directory, either manually or by using the 'shutdown'
# command from within the MUD.
#
# Creating a file called .fastboot makes the script wait only 5 seconds
# between reboot attempts instead of the usual 60.  If you want a quick
# reboot, use the "shutdown reboot" command from within the MUD.
#
# Creating a file called .killscript makes the script terminate (i.e., stop
# rebooting the MUD).  If you want to shut down the MUD and make it stay
# shut down, use the "shutdown die" command from within the MUD.
#
# Finally, if a file called pause exists, the script will not reboot the MUD
# again until pause is removed.  This is useful if you want to turn the MUD
# off for a couple of minutes and then bring it back up without killing the
# script.  Type "shutdown pause" from within the MUD to activate this feature.
#

#. /home/aol/production/bin/unlimit_resources

# The port on which to run the MUD
PORT=9080

# Default flags to pass to the MUD server (see admin.txt for a description
# of all flags).
FLAGS='-q -p'

#############################################################################

while ( : ) do

  DATE=`date`
  echo "autorun starting game $DATE" >> log/syslog
  echo "running bin/circle $FLAGS $PORT" >> log/syslog

  bin/circle -q $PORT >> log/syslog 2>&1

  tail -30 log/syslog > log/syslog.CRASH

  fgrep "Multiplay detected from" log/syslog >> log/multiplay.log
  fgrep "self-delete" log/syslog >> log/delete.log
  fgrep "death trap" log/syslog >> log/dts.log
  fgrep "killed" log/syslog >> log/rip.log
  fgrep "Running" log/syslog >> log/restarts.log
  fgrep "advanced" log/syslog >> log/levels.log
  fgrep "equipment lost" log/syslog >> log/rentgone.log
  fgrep "usage" log/syslog >> log/usage.log
  fgrep "new player" log/syslog >> log/newplayers.log
  fgrep "SYSERR" log/syslog >> log/errors.log
  fgrep "(GC)" log/syslog >> log/godcmds.log
  fgrep "Bad PW" log/syslog >> log/badpws.log
  fgrep "PC Killer" log/syslog >> log/PCKiller.log
  fgrep "PC vs PC" log/syslog >> log/PCKiller.log
  fgrep "edit" log/syslog >> log/edits.log
  fgrep "approved" log/syslog >> log/approvals.log
  fgrep "reject" log/syslog >> log/rejections.log
  fgrep '(prayer)' log/syslog >> log/prayer.log

  rm log/syslog.1
  mv log/syslog.2 log/syslog.1
  mv log/syslog.3 log/syslog.2
  mv log/syslog.4 log/syslog.3
  mv log/syslog.5 log/syslog.4
  mv log/syslog.6 log/syslog.5
  mv log/syslog.7 log/syslog.6
  mv log/syslog.8 log/syslog.7
  mv log/syslog.9 log/syslog.8
  mv log/syslog   log/syslog.9
  mv log/prayer.log log/prayer.1

  touch log/syslog

  if [ -r .killscript ]; then
    DATE=`date`;
    echo "autoscript killed $DATE" >> syslog
    rm .killscript
    exit
  fi

  if [ ! -r .fastboot ]; then
    sleep 15
  else
    rm .fastboot
    sleep 5
  fi

  while [ -r pause ]; do
    sleep 10
  done

done
